tramhao/termusic

- README.md
Made gstreamer and youtbe-dl links that lead to the respective installation pages.
> update: add links to gstreamer and youtube-dl.

- src/main.rs
Signed-off-by: Serial <69764315+Serial-ATA@users.noreply.github.com>
This just removes some repetition in main.rs
> DRY in main.rs

- CHANGELOG.md
- README.md
Signed-off-by: Serial <69764315+Serial-ATA@users.noreply.github.com>
This moves the changelog to CHANGELOG.md and makes dependencies clearer
> Cleanup README.md

- src/invidious.rs
I came across this piece of code while I was looking at the changes in the latest release. I thought it was looking ugly and it can be simplified.
P.S. `parse_instance` method returns a tuple of instance URI and health but it can be wrapped into a struct in the future I think.
> refactor(invidious): simplify parsing instances

- src/player/rusty_backend/cpal/host/alsa/mod.rs
- src/player/rusty_backend/cpal/host/wasapi/device.rs
- src/player/rusty_backend/cpal/host/wasapi/mod.rs
- src/player/rusty_backend/cpal/host/wasapi/stream.rs
- src/player/rusty_backend/cpal/mod.rs
Fixes #19.
I haven't tested too much but it seems to work okay! Most of the changes were just clippy warnings.
> Windows support

- CHANGELOG.md
This PR is doing what the title suggests 🐻
> docs(changelog): fix typos

- tui/src/main.rs
Makes the `main` function easier to read in my opinion.
> refactoring tui/src/main.rs

- lib/Cargo.toml
- lib/src/config/theme.rs
- playback/src/gstreamer_backend.rs
- playback/src/playlist.rs
- tui/src/ui/components/playlist.rs
- tui/src/ui/components/progress.rs
- tui/src/ui/mod.rs
- tui/src/ui/model/mod.rs
Fixes a bug where .opus files can not be added to the playlist even with the `gst` feature.
> Bugfix no opus on gst

- lib/src/songtag/mod.rs
- tui/src/main.rs
- tui/src/ui/components/config_editor/key_combo.rs
- tui/src/ui/components/podcast.rs
- tui/src/ui/components/tag_editor/te_counter_delete_lyric.rs
- tui/src/ui/model/update.rs
- tui/src/ui/model/youtube_options.rs
This PR adds onto #168 by fixing the clippy errors from the CI (hopefully)
> style: apply clippy --fix

- lib/src/config/key.rs
- lib/src/config/mod.rs
- lib/src/config/theme.rs
- lib/src/invidious.rs
- lib/src/types.rs
- playback/src/playlist.rs
had to do this so i could log stuff like in https://github.com/tramhao/termusic/issues/161#issuecomment-1826381709
> refactor(lib::config): derive "Debug" for "Settings" (and all lower structs)

- playback/src/mpris.rs
This PR changes mpris to actually set & update the position of the currently playing track (and not just report the length).
fixes #185
> feat(playback::mpris): set & update position

- server/src/server.rs
This PR changes the server so that the address used is printed (if successful) and also fails if the binding fails (before this PR the server's "player_handle" continues to run, even if binding fails and only errors once that handle exits)
> feat(server): print used address and actually fail if binding fails

- Cargo.lock
- Cargo.toml
- playback/src/mpris.rs
~~This PR requires / is build on #193; do not merge this current PR first!~~
This PR updates dependency `souvlaki` (generic mpris), but i still wanna wait for some feedback on https://github.com/Sinono3/souvlaki/issues/46, because that version bumped the MSRV to 1.74
> Update dependency `souvlaki`

- server/src/music_player_service.rs
This PR simplifies some things in the `server::music_player_service` module
> Music service refactor

- playback/src/gstreamer_backend.rs
This PR fixes gstreamer's EOS handling again, this time actually for multiple tracks (while gapless is enabled).
some further explanation:
> as for the track change issue, it was a simple race-condition i didnt consider, pushing a PR in a sec
the "race-condition" was that in the `gst::MessageView::StreamStart` handling a `PlayerCmd::Eos` message was sent, but then `eos_watcher` was immediately set  to `false`, where as in the `PlayerCmd::Eos` handling, the `eos_watcher` was set to `true` again.
re https://github.com/tramhao/termusic/issues/232#issuecomment-1994451783
> fix(playback::gstreamer): use different event for "skip_one" than "EOS"

- playback/src/lib.rs
- tui/src/ui/components/mod.rs
- tui/src/ui/components/tag_editor/view.rs
- tui/src/ui/components/xywh.rs
- tui/src/ui/model/update.rs
This PR does various small style changes, including:
- remove long unused code / imports
- inline some feature-gated imports
> Various small Style changes

- .github/workflows/release.yml
This PR tries to fix the invalid CI config as per https://github.com/tramhao/termusic/issues/259#issuecomment-2016536686
> chore(workflows/release): try fixing invalid config

- tui/src/ui/components/popups/error.rs
This PR adds handling for `global_quit` and `global_esc` key to close the error popup (like other popups)
> fix(tui::ui::components::popups::error): also close popup on global_quit or global_esc

- tui/src/ui/components/config_editor/key_combo.rs
- tui/src/ui/components/popups/deleteconfirm.rs
- tui/src/ui/components/popups/general_search.rs
- tui/src/ui/components/popups/help.rs
- tui/src/ui/components/popups/podcast.rs
- tui/src/ui/components/popups/quit.rs
- tui/src/ui/components/popups/saveplaylist.rs
This PR changes the components titles to be consistent in spacing.
fixes #fixes #273
> Consistent component title

- lib/src/songtag/encrypt.rs
This PR changes the static vectors to be const byte slices, which should somewhat reduce the cost and make the code cleaner.
Also comment-out the RSA_KEY as it is not used.
This is something i noticed while doing #286 and i just couldnt let it stay like it was.
> refactor(lib::songtag::encrypt): use const byte slices over static vectors

- Cargo.toml
re 872e96971966eb1fcd0e6165d92ca9ef18756bc2
> deps(yaml-rust): remove again

- playback/src/gstreamer_backend.rs
This PR abstracts the playbin so that it can be cloned and called from different threads (moved), it also does:
- add `PlayerInternalCmd` so that we are actually exhaustive in the matching and less confusion about what sender / receiver goes where
- actually handle the `Buffering` messages as the gstreamer documentation wants (setting state to pause / playing)
the ultimate goal was to remove the speed-hack that is in place, but i failed at that as i couldnt find a place to properly apply the seek event on initial start and track change (i always ran into issues like the queries position still being of the old track or heavy audio cracking on skip to next track or no speed being applied at all)
> Refactor GStreamer backend to have a abstracted Playbin

- lib/src/invidious.rs
- lib/src/types.rs
- tui/src/ui/model/youtube_options.rs
instead of "reqwest::blocking"
> Refactor `lib::invidious` to use async-reqwest

- playback/src/rusty_backend/mod.rs
quick-fix to allow "skip to next" and "skip to previous" to still work when the sink is empty, as otherwise we wait for a EOS, which will never come. this case can happen if enqueuing a track has failed (like unsupported format).
in the future, this should be handled more gracefully than just in "skip" (like automatically trying to go to the next track on enqueue error).
enqueue error (somewhat unrelated to this PR) also result in things described like `when I click on an episode to play, termuisc player feezes, although it allows me to quit, and restart.` (#306) as the error does not get passed to the TUI.
> fix(playback::rusty): send EOS on SKIP with empty sink

- lib/src/config/theme.rs
- lib/src/songtag/lrc.rs
- lib/src/songtag/migu/model.rs
- lib/src/songtag/netease/mod.rs
- lib/src/songtag/netease/model.rs
- playback/src/rusty_backend/conversions/channels.rs
- playback/src/rusty_backend/icy_metadata.rs
- playback/src/rusty_backend/source/mod.rs
- playback/src/rusty_backend/source/scaletempo/mod.rs
- tui/src/cli.rs
- tui/src/ui/components/database.rs
- tui/src/ui/components/lyric.rs
This PR applies all suggestions / warnings from rust 1.78 rustc and clippy.
in addition also applies some suggestions to tests.
> Fix suggestions & warnings from rust 1.78

- lib/src/config/key.rs
- lib/src/invidious.rs
- lib/src/songtag/mod.rs
- lib/src/utils/mod.rs
- playback/src/playlist.rs
- tui/src/ui/components/config_editor/key_combo.rs
- tui/src/ui/components/config_editor/view.rs
- tui/src/ui/components/podcast.rs
- tui/src/ui/model/update.rs
- tui/src/ui/model/youtube_options.rs
Improves some messages and error messages that I encountered in the app or greped.
> chore(typo): improve localization

- CHANGELOG.md
- lib/src/lib.rs
- lib/src/utils.rs
- server/src/cli.rs
- server/src/server.rs
- tui/src/cli.rs
- tui/src/main.rs
This PR does some small cli things:
- remove option `disable_cover` from the server binary
- actually make use of `action` (subcommands) in the server binary
- some small clean-up and doc-comment updates
> Fix some CLI things

- lib/src/library_db/mod.rs
- tui/src/ui/components/config_editor/update.rs
- tui/src/ui/components/config_editor/view.rs
- tui/src/ui/components/database.rs
- tui/src/ui/components/lyric.rs
- tui/src/ui/components/music_library.rs
- tui/src/ui/components/playlist.rs
- tui/src/ui/components/podcast.rs
- tui/src/ui/components/popups/podcast.rs
- tui/src/ui/model/mod.rs
- tui/src/ui/model/update.rs
- tui/src/ui/model/view.rs
This PR sorts, renames and separates out TUI `Model` fields to be more logical and quick(er) to understand at a glance
> Sort & separate out tui `Model` fields

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
This PR updates some markdown docs to fix some small "errors" like stray whitespaces.
Also reword much in the README to represent the current state.
> Update & fix some markdown docs

- lib/src/track.rs
MPEG files were being read twice to get the language and description for USLT frames. Since Lofty [0.20.0](https://github.com/Serial-ATA/lofty-rs/releases/tag/0.20.0), `TagItem` is able to retain both of those fields.
> refactor(lib): remove special MPEG tag handling

- lib/src/types.rs
- tui/src/ui/model/youtube_options.rs
This PR is a slight cleanup of the extra ytdl argument changes.
re #486
> Some fixes atop extra ytdl arguments

- tui/src/ui/model/youtube_options.rs
This PR hopefully fixes what has been discussed in #486.
Given the string input `--something Path --else`, it now generates from `convert_to_args`:
```txt
DEBUG [
Arg {
arg: "--something",
input: Some(
"Path",
),
},
Arg {
arg: "--else",
input: None,
},
]
```
I have also removed the splitting from `--something=Path` as that is something that has semantic meaning and should be handled by the command (ytdlp in this case) directly.
@tramhao can you confirm this is what you were talking about?
> fix(tui::ui::model::youtube_options::convert_to_args): correctly convert Arguments with values

- playback/src/lib.rs
automatically done by "cargo clippy --fix"
> style: apply fixes for rust 1.89

- lib/src/config/v2/tui/keys/mod.rs
- lib/src/track.rs
- tui/src/ui/components/config_editor/update.rs
- tui/src/ui/components/music_library.rs
- tui/src/ui/model/youtube_options.rs
in preparation of 1.90 in a few days.
new: [implicit_clone](https://rust-lang.github.io/rust-clippy/master/index.html#implicit_clone)
> style: fix clippy warnings in nightly
