src/player/rusty_backend/source/periodic.rs

This just makes use of `saturating_sub` so you don't have to force a nonzero `update_frequency` :)

Remove overflow prevention hack

---

src/song.rs
src/ui/components/playlist.rs
src/ui/model/view.rs

Signed-off-by: Serial <69764315+Serial-ATA@users.noreply.github.com>
This has the following fixes:
* Removes the `FromStr` impl, replacing it with a more generic `Song::read_from_path`
* Fixes the insertion of lyrics in `Song::save_tag`
* `Tag::insert_text` replaces any existing lyrics, you need `Tag::push_item` :)
* Removes the mp3 extension assumption in `Song::rename_by_tag` if there is no extension
* Added `update_tag` to remove some repetition
* When reading a `Song` from a path, fields are set as the information comes, rather than needing *both* the file to be read and a tag to exist
* This just makes it so the `duration` and `file_type` fields can still be used with a file with no tags

Cleanup `Song` impl

---

README.md

Signed-off-by: Serial <69764315+Serial-ATA@users.noreply.github.com>
AAC, ALAC, and PCM are unlikely to be used outside of a container format (m4a, wav, etc). This should make the format table a little neater.
I switched AAC-LC to ADTS, which doesn't have metadata support.

Remove some codecs from format table

---

README.md

Just noting that the config.toml is in the Application Support dir on macOS.

Note the config file path for macOS

---

Cargo.lock
Cargo.toml

Fixes #111
[lofty 0.10](https://crates.io/crates/lofty) was yanked, along with one of its depencies: [ogg_pager 0.5](https://crates.io/crates/ogg_pager)
This PR simply bumps lofty to 0.11 and ogg_pager to 0.5, fixing an error that prevents users from installing termusic directly from crates.io with the `cargo install termusic` command, and avoids using yanked dependencies.

bump lofty to 0.11, up from 0.10 (yanked)

---

src/player/playlist.rs

Modified for the enums Status and Loop to appease Clippy and stop CI from failing

Fixed clippy lint `deriveable_impls`

---

playback/src/rusty_backend/decoder/mod.rs
playback/src/rusty_backend/stream.rs
tui/src/ui/components/xywh.rs

This PR applies `cargo fmt`, because the current tests are failing because of it

style: fix format (cargo fmt)

---

tui/src/ui/model/mod.rs

This PR adds a panic hook to reset the screen before printing the panic message
this is likely not ideal because TerminalBridge cannot be cloned, but works
re #161

fix(tui): add panic hook to reset the screen before printing panic

---

tui/src/ui/mod.rs
tui/src/ui/model/mod.rs

This PR uses some changes from #151, so that debug builds are even possible to be run and not crash (without extra new features like in the mentioned PR)

fix: fix debug builds by spawning a blocking tokio thread

---

lib/src/utils/mod.rs
tui/src/main.rs

This PR changes the TUI daemon spawning process to try to look for the binary adjacent to the currently executing exe, which will allow running `cargo run --bin=termusic` and not cause a issue like `No such file or directory`.
This check could likely be improved to also check for permissions before being used, but for now i know this is working for the simple case of running it when not installed (or in PATH)

fix(tui): try to find the daemon binary adjacent to the current exe

---

lib/src/utils/mod.rs
tui/src/main.rs

This PR changes `spawn_process` to return a result so it can be handled by the calling function instead.
Alternatively the expect in the function originally could include what failed to spawn, but this would only indirectly hint at the line which actually is a error (ie the calling function, see error).
I ran into this trying to run binary `termusic` without having `termusic-server` build.
error before this PR:
```txt
thread 'main' panicked at /mnt/projects/rust/termusic/lib/src/utils/mod.rs:473:17:
Error spawning server process.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
error after this PR:
```txt
thread 'main' panicked at tui/src/main.rs:109:83:
Could not find termusic-server …
```

fix(lib::utils::spawn_process): return Result

---

tui/src/main.rs

likely because of #155, #154 and #157
also removes the unused functions added by #154
#154 added some functions to outsource some functions (like checking for the daemon and starting it), but #157 changed it so that they depend on each-other (and it was merged so that the functions added by #154 were unused).
the full logic could likely be outsourced to another function (instead of individual functions)

fix(main): fix all build errors because of recent merges

---

.github/workflows/build.yml
.github/workflows/release.yml

This PR changes the actions used in the workflows to non-deprecated versions
NOTE: please wait until the CI is finished with this one, so that we know there are no problems with the actions
another NOTE: the release run will have to be tested separately because it does not run for a CI (and i am unsure of the changes i have done for `actions-rs/cargo`)
PS: the cross/cargo steps could likely be combined by changing the matrix value to set which to use (instead of `cross: true` use `command: cross` and `cross: false` `command: cargo`), but for now i have gone with that

Change actions used in workflows

---

lib/src/podcast/db.rs
lib/src/podcast/mod.rs
lib/src/songtag/encrypt.rs
lib/src/songtag/mod.rs
lib/src/sqlite.rs
lib/src/track.rs
playback/src/lib.rs
playback/src/playlist.rs
playback/src/rusty_backend/mod.rs
server/src/server.rs
tui/src/main.rs

This PR fixes all rustc and clippy warnings, some by refactoring. in more detail:
- mostly appease clippy by converting `.expect`s to return results instead where possible
- add `# Panics` (and `# Errors`) headers where clippy wants them
- refactor some functions to return results
- outsource podcast `download_list` job to its own function (because it does not actually panic, but the job being sent does)
- in `GeneralPlayer::start_player` use a single-threaded runtime instead, because it will block the current thread anyway (so less overhead)
- add a todo to the `PlayerTrait` to sync the return types of `seek` and `seek_to` (because why would they return different hings?)
- change `playback::rusty_backend::Player::seek` to use `self.command` like surrounding functions
- remove return type …

Fix all warnings

---

server/Cargo.toml
server/src/cli.rs
server/src/logger.rs
server/src/server.rs
tui/src/cli.rs

This PR fixes the broken merge done in #172, in more detail:
- fixes that #172 was still based on before the revert of #154, which meant the merge in #172 re-added a dependency which was not defined in the workspace
- #172 was not properly formatted (cargo fmt & cargo clippy)
- #172 still had the out-standing issue that the default logfile path would not work on non-posix systems

Fix broken merge of #172

---

tui/src/ui/components/config_editor/general.rs

fixes #161
This PR fixes #161, i am not totally sure on why this is necessary in the first place, but adding a guard if it should be empty.
not using `saturating_sub` because it seems like it will panic if the string is empty:
`cannot remove a char from the end of a string`

fix(tui::config_editor::general): fix panic if "music_dir" is empty

---

playback/src/mpris.rs

This PR adds mpris duration metadata
tested & working in KDE Plasma Wayland 5.27.9 (uses the same method MPV does)

feat(playback::mpris): add duration metadata

---

Cargo.lock
playback/Cargo.toml
playback/src/mpris.rs

fixes #178
This PR adds the `mpris:artUrl` metadata and so displays cover-art in mpris
tested & working in KDE Plasma Wayland 5.27.9 (uses the same method MPV does)

feat(playback::mpris): display coverart if available

---

playback/src/mpris.rs

This is a fixup to #179, at the time i didnt notice that the `Picture` type had a `mime_type` associated with it and assume it is always a jpeg, this PR fixes it
(tested on the same system as #179, i dont have any png or gif songs, but jpeg still works)

fix(playback::mpris): use correct mime-type of picture

---

Cargo.lock
Cargo.toml
server/src/logger.rs
server/src/server.rs
tui/src/logger.rs
tui/src/main.rs
tui/src/ui/mod.rs

This PR does a bunch of logging improvements that i have noticed, in more detail:
- reset terminal regardless what the main-loop result is
- add panic hooks in loggers to print panics to logs
- print `main` Result::Err(ors) to the log
- enable anyhow `backtrace` to get a full trace of where a error originates if `RUST_BACKTRACE` is set to a truthy value (`1` or `true`)

Logging improvements

---

.github/workflows/build.yml
Cargo.toml
lib/Cargo.toml
playback/Cargo.toml
rust-toolchain.toml
server/Cargo.toml
tui/Cargo.toml

This PR adds a entry to test the mentioned MSRV in the CI (for now only linux), in addition also does:
- remove `rust-toolchain.toml`, because it only sets `stable`, which is not useful and would require workarounds for CI
- update rust-cache github action
- add `rust-version` field in `Cargo.toml`s
- run `build` action on all branches, not just master (useful for feature work or CI testing, etc)
*MSRV is based on the one mentioned in the README

CI test mentioned MSRV

---

lib/src/types.rs
playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpris.rs
playback/src/mpv_backend/mod.rs
playback/src/playlist.rs
playback/src/rusty_backend/mod.rs
playback/src/rusty_backend/sink.rs
server/src/server.rs
tui/src/main.rs

This PR has some many minor (possible unrelated) changes, which i found while trying to do something else, changes include:
- fix possible panic on track end (could not 100% reproduce this, but changing to use `saturated_sub` fixed it)
- pass on argument `--log-filecolor` to the started server (like `--log-to-file`)
- add some doc-comments to better get to know what is for what and what parameters are expected (there are still some TODO's, like `Cmus*Queue`)
- add names to spawned threads to better differentiate if a thread crashes or while using gdb
- refactor `playback::playlist::load` to not use a intermediate vector
- refactor `playback::playlist` to use a common way to get the `playlist.log` file path (reducing chance of changing one place but not others, also DRY)
- block on channel …

Multiple small changes

---

Cargo.lock
Cargo.toml
playback/src/gstreamer_backend.rs

~~This PR requires / is build on #193; do not merge this current PR first!~~
This PR updates dependencies `gstreamer` and `glib`, this is a WIP because i had to disable some code, but i am not sure what it did, also because of a deprecation function that is still in use:
```txt
warning: use of deprecated associated function `glib::main_context_channel::<impl glib::MainContext>::channel`: Use an async channel, from async-channel for example, on the main context using spawn_future_local() instead
--> playback/src/gstreamer_backend.rs:128:47
|
128 |         let (main_tx, main_rx) = MainContext::channel(glib::Priority::default());
|                                               ^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: `termusic-playback` (lib) generated 1 warning
```

Update dependencies `gstreamer` and `glib`

---

lib/src/config/theme.rs
lib/src/types.rs
playback/src/playlist.rs
tui/src/ui/components/config_editor/color.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/playlist.rs
tui/src/ui/model/update.rs

This PR adds a symbol to the currently playing track in the playlist:
This PR builds on the original commit of 5b2b5cf24d6c6ba9d4ce6e6d5e9ed7e61aef51d8 (part of #154), but enhances it so that it is actually configurable (like the other symbols)
Note: i am personally not happy with:
- the way it gets added and needs a full playlist re-sync to remove it from one title and add it onto another (instead of operating on the table directly)
- the way it looks / where the symbol is placed; it looks like it is part of the track name, but i didnt / dont know how to put it somewhere like the highlight symbol (cursor)
as for the location the config where this field is placed, it is right under `Playlist Highlight Symbol` (in the playlist column), because i didnt know a better place to put it
fixes …

Add a Currently Playing Symbol

---

playback/src/mpris.rs
server/src/server.rs

This PR adds some more commands to be supported from `souvlaki`(`mpris.rs`):
- `Seek(direction)`: seek a undetermined amount in a direction (only used in windows, according to source-code), making use of the `seek_relative` function (amount specified by config)
- `SeekBy(direction, duration)`: seek a specified amount in a direction (used by [mpris `Seek`](https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Method:Seek), in microseconds)
- `Quit`: quit the player
- `SetPosition(duration)`: seek to a specific point in the track
This PR also adds a log message on `PlayerCmd::Quit` to indicate why the server exited

Support some more souvlaki media commands

---

playback/src/rusty_backend/mod.rs
playback/src/rusty_backend/sink.rs

This PR fixes the issue(s) added by #196 and #197, while also cleaning up some of the total_duration duplication, in more detail:
- move to use `type` for total_duration(s) instead of having to write it out every time
- refactor to not have duplicate `total_duration` (once arc-mutex and once as a thread local)
- add a new player-internal command `Eos` (same as `PlayerCmd::Eos`)
- store enqueued duration as a thread variable, and set it as current_duration on EOS
Notes on the current implementation: the current QueueNext implementation on storing durations only works for 1 enqueued after the currently playing and will break if there should be more enqueued into the sink.
also i dont quite like how it is stored as such a variable instead of being stored / gotten from the media-stream / …

Refactor rusty_backend queue duration

---

playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpris.rs
playback/src/mpv_backend/mod.rs
playback/src/rusty_backend/mod.rs
playback/src/rusty_backend/sink.rs
server/src/music_player_service.rs
server/src/server.rs

This PR expands on a297816754ab4672752f3d67a484bdc61bf32674 (part of #154), which refactors channels for `PlayerCmd`, which includes:
- making a alias for the type, so it is easily used and referenced across many places
- remove `Arc<Mutex<` around the tokio channels, because they themself are `Send + Sync + Clone` (on both receiver and sender)
This PR will very likely conflict with ~~#196~~ and #197

Refactor some channel related types in playback

---

playback/src/rusty_backend/decoder/buffered_source.rs
playback/src/rusty_backend/decoder/mod.rs
playback/src/rusty_backend/mod.rs

~~This PR is based on #205, do not merge this current PR first~~
This PR buffers all source files using a 4MiB `BufReader`, which is lower if the file-size is lower (to not waste memory); also in the future the capacity could be configurable.
re #191
also see https://github.com/pdeljanov/Symphonia/discussions/260
~~WIP: because of the based-on PR and because i wanted a reply first from https://github.com/pdeljanov/Symphonia/discussions/260~~

Rusty decoder buffered files

---

.github/workflows/build.yml
playback/Cargo.toml

This PR fixed what was broken by f4ed6659baaad449ad1b40c58760db65dbcb2d21, also adding some notes to prevent it in the future.
In addition i tested around with enabling `all-backends` in CI, but failed, but got some things to document for the future (package names)

Fix build and CI

---

playback/src/gstreamer_backend.rs
playback/src/lib.rs
server/src/server.rs

This PR does a variety of thing to the `gst_backend`, most notably: fixing #192 and applying https://github.com/tramhao/termusic/commit/f4ed6659baaad449ad1b40c58760db65dbcb2d21#commitcomment-138909846, in more detail:
- apply https://github.com/tramhao/termusic/commit/f4ed6659baaad449ad1b40c58760db65dbcb2d21#commitcomment-138909846 so that gst events actually get send again
- replace glib warnings / errors with rust log ones
- remove only written-to (and otherwise unused) property `duration`
- remove only written-to (and otherwise unused) property `paused`
- clean-up some commented-out code
- allow volume above 100 (because gst allows it) (currently gets clamped somewhere else on set, but reads higher values from config just fine)
- change `is_paused` to check against specific states and …

Gst updates

---

playback/src/lib.rs
playback/src/mpris.rs
server/src/server.rs

This PR updates `server/src/server.rs` to be less indented and work better, in more details:
- move ticker thread from `playback` into `server`
- remove much indentation
- change player loop to be `while let Some`, so that it exits on channel close
- change ticker thread to be `while let Some`, so that it exists on channel close
- return result of player task on failure (instead of ignoring)
- change tonic music server to be a task instead (server now actually exits when the player dies)
- add a name to the ticker thread
- fix a comment in mpris

Server main file refactor & fixes

---

lib/src/songtag/lrc.rs
lib/src/track.rs
playback/proto/player.proto
playback/src/discord.rs
playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpris.rs
playback/src/mpv_backend/mod.rs
playback/src/rusty_backend/mod.rs
playback/src/rusty_backend/sink.rs
server/src/music_player_service.rs
server/src/server.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/progress.rs
tui/src/ui/mod.rs
tui/src/ui/model/mod.rs
tui/src/ui/playback.rs

This PR refactors "all" places (`PlayerTrait`, Backends, gRPC, TUI) to use `Duration` instead of `i64` (or even `u32` or `i32`).
There are some tangential things i have done:
- change mpv to listen on `Double`(`f64`)s instead of `Int64`(`i64`) (way more precision than just a second)
- add some doc-comments to `lrc`
- change music-player-service's shared state to be separate from the response (easier to use)
@tramhao please let me know if everything as `Duration` is fine, or should we use something like gst's `u64` which is nano seconds, or mpv's `double`(`f64`) storing(or at least for transfer) seconds?

Refactor to use and store `Duration` instead of `i64`

---

playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpv_backend/mod.rs
playback/src/rusty_backend/mod.rs
server/src/server.rs

This PR touches the definition of seeking slightly, in more details:
- remove a TODO which was added (and also done) in #216 (which i forgot to remove)
- add doc-comments to seek definition
- change (and consistentize) `seek_to` parameter name
- allow `seek_to` to be more precise in all backends (rusty, mpv, gst)
- rusty backend: rename a event to be more obvious what it is

Slight refactoring of seeking

---

lib/src/config/mod.rs
playback/proto/player.proto
playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpris.rs
playback/src/mpv_backend/mod.rs
playback/src/rusty_backend/mod.rs
server/src/music_player_service.rs
server/src/server.rs
tui/src/ui/mod.rs
tui/src/ui/playback.rs

This PR refactors `PlayerTrait`'s volume functions to take / return `u16`, including all backends and config, in more details:
- store volume as `u16` on all backends instead of `i32`
- store volume as `u16` in the config (which makes configs invalid which have negative volumes or way too high of volumes; which requires manual editing to even achieve)
- change proto definition to use `uint32` (no sizes below 32 bits are available in protobuf)
Why `u16` instead of something else like staying with `i32` or using `f32`?
I think `u16` is the best choice for the current spec, because:
- volume is never negative so signed values (`i*`) should fall out (as half would never be used)
- we are currently using volume as percent (both in tui, settings and config), so changing to floats (without the * …

Refactor `PlayerTrait`'s volume

---

README.md
server/build.rs
server/src/cli.rs
tui/build.rs
tui/src/cli.rs

This PR changes it so that `--version` better represents what actual version is in use.
This means now `git` (and being in the repository) is a required build dependency.
new possible formats:
`Termusic v0.7.11` - release
`Termusic v0.7.11-302-g63396ee5` - nightly (or only commited changes)
`Termusic v0.7.11-302-g63396ee5-dirty` - dev (uncommited changes)
`unknown` - `git` is missing or errored (like not being in a repository)
explanation of the different parts:
`Termusic` is the binary name (first letter capitalized)
`v0.7.11` is the latest tag on the branch
`302` is the number of commits since the tag
`g63396ee5` is 2 parts, the `g` in the beginning means `git`
the rest `63396ee5` is the abbreviated commit sha
`dirty` indicates the build has uncommited changes
These changes *should* …

Better version in `--version` via git

---

lib/src/ueberzug.rs
tui/src/ui/components/xywh.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/view.rs

This PR refactors how `ueberzug` is handled in error cases and windows, in more detail:
- dont re-try starting `ueberzug` on a permanent error (like binary not found)
- disable `ueberzug` even if feature `cover` is enabled on `windows`
- some general de-duplication in `ueberzug` instance
fixes #202 
PS: i do not know if the `not(target_os = "windows")` also affect mingw as i didnt find any documentation if mingw counts as that `target_os`

Refactor `ueberzug` instance

---

README.md

Ueberzug original repository was abandonned by its author. It was forked under a new organization for some time which is the new point of reference for distros.
Ueberzugpp is a drop-in replacement written in C++.
As those were mentioned twice in README, I hesitated if first occurrence would need links too, and could also write it something like `ueberzug[pp]` instead of the way I did.
I was not sure if README was the place to mention that `ueberzugpp` was a drop-in replacement, so I opted for not write it there. I can update those depending on feedbacks, of course.

Update uerberzug references in README

---

playback/src/discord.rs
playback/src/gstreamer_backend.rs
playback/src/mpv_backend/mod.rs
playback/src/rusty_backend/mod.rs
server/build.rs
server/src/cli.rs
tui/build.rs
tui/src/cli.rs

This PR does some QoL improvements, namely:
- allow building termusic without git or `.git` and fall-back to the Cargo.toml version (with indicators), this is for example used for [`termusic` AUR](https://aur.archlinux.org/packages/termusic)
- allow setting the backend via a environment variable (`TMS_BACKEND`)
- add a thread name to discord's thread
- consistent `VOLUME_STEP` for backends
- all backends: change internal-only fields to be non-public
- gstreamer: reduce amount of channel's needed / channel proxying
- some slight formatting things

Some Quality-of-Life improvements

---

Cargo.lock
Cargo.toml
lib/src/track.rs
playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpv_backend/mod.rs
playback/src/rusty_backend/mod.rs
stream/Cargo.toml
stream/src/lib.rs

Let me say that i am sorry to not split these changes, but they somewhat work hand-in-hand with each-other.
This PR does (sorted by most significant first):
- refactor `playback::PlayerTrait::enqueue_next` to pass along a `&Track` instead of a `&str` (to be in-sync with `::add_and_play`)
- rusty backend: use the same matching for `QueueNext` as `Play` has, fixes #210
- stream: actually stop downloading once the source is dropped, re https://github.com/tramhao/termusic/issues/210#issuecomment-1954409018
- stream: add a more proper name to the temporary file (so it can be identified, instead of `.tmpXXXX` it is now `.termusic-stream-cache-XXXX`)
- inline all duplicate (single / double line) functions in all backends that are meant to be called via the trait
- add some documentation here and …

Refactor `PlayerTrait::enqueue_next` to pass a track, and some Rusty backend refactors

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
lib/src/utils/mod.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/progress.rs

This PR fixes some things regarding recent commits, which includes:
- update the MSRV in the README
- add changes to CHANGELOG since last such commit
- revert the upgrade to tuirealm 1.9 as https://github.com/veeso/tui-realm/issues/70 (and https://github.com/veeso/tui-realm/issues/71)
*1 this mean if you use any kind of mouse event (which includes *hovering*), the TUI's input is basically locked-up and fix you have some kind of exit event (like `q`) and then have some mouse events again, those events will be spammed to the terminal.
also i think we can do better than having to do manual changes to the `config.toml`
Edit: changed `tuirealm#64` to `tuirealm#70`

Fix some thing regarding the recent commits

---

tui/src/ui/model/view.rs

This PR changes the TUI displayed version to be the same as `--version`.
But maybe consider moving the version display to some other place like `Help`, `Config` or a new `About` window.

fix(tui::ui::model::view): use same version clap uses to display

---

CHANGELOG.md
tui/src/ui/components/database.rs

This PR changes the displayed Track's name to be the title instead of the filename for `Database -> Tracks`

fix(tui::ui::components::database): show track title instead of filename for "Tracks" in "Database"

---

CHANGELOG.md
stream/src/http.rs

This PR changes the radio title parsing to be its own function and overwrite the full string instead of appending, in more details:
- dont append new title to old
- move parsing to own function for better code clarity and direct testing
- parse until `';` instead of just `'` (for things like `Don't`)
- add tests for the parsing
Now instead of `Currently Playing:  Artist - Some Title - Artist - Some other Title - Artist - Some other other Title` it will only display `Currently Playing: Artist - Some other other Title`
also somehow before this PR sometimes the string would just go blank and never recover for reasons unknown to me, but now it seemingly does not anymore

Refactor radio title parsing

---

CHANGELOG.md
tui/src/ui/components/config_editor/mod.rs
tui/src/ui/components/popups.rs

This PR adds keybindings for `Y` and `N` to the `QuitPopup` to confirm the choices.
Please note that i am not proficient in tuirealm, so i dont if i set it properly (it looks quite verbose to me)
fixes #108

QuitPopup & ConfigSavePopup: allow confirming choices with "Y" and "N"

---

Cargo.lock
Cargo.toml
playback/src/rusty_backend/mod.rs

This PR updates `stream-download` which added the ability to change the prefix for the temporary files (which we already used before switching to `stream-download`)

Update `stream-download` and set a custom temporary file prefix

---

lib/src/track.rs
playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/playlist.rs
playback/src/rusty_backend/mod.rs
server/src/server.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/podcast.rs
tui/src/ui/components/progress.rs
tui/src/ui/components/xywh.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs

This PR changes `Track`'s `media_type` to not be option, as it has not been used optionally. also a track should likely always identify what type it is.

refactor(lib::track): change "media_type" to be non-optional

---

playback/src/lib.rs
playback/src/rusty_backend/mod.rs
server/src/server.rs

This PR does:
- convert `rusty_backend::queue_next` to always return Results instead of just logging `error!`
- dont construct a new tokio runtime, use the current one already available*1
- move `server`'s main command handling loop to own function
- move `server`'s main command handling loop to be its own thread instead of tokio's spawn_blocking ([more adhering to](https://ryhl.io/blog/async-what-is-blocking/))
*1 in the future, we could convert that function to also be async

Refactor rusty_backend function to properly return results & move main player loop to own function

---

tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/tag_editor/view.rs
tui/src/ui/model/view.rs

This PR changes some `assert!` macros to be `.expect` because `assert!` includes the full code it gets passed in the binary to print on error.
stats:
format: master(e85f574a48befbf4a53560ec8a2200a350c987dd) -> this pr(e77b6897cf705f44f45520f7b37777f1f81fa99d)
features: default + `all-backends`
both versions build using the same system libraries and linker
debug:
termusic: `312232568 bytes` (298M) -> `312004360 bytes` (298M) [`-228208 bytes`, ~ -222KB]
termusic-server: `292698264 bytes` (280M) -> `292698264 bytes` (280M) [-0]
release:
termusic: `30696952 bytes` (30M) -> `30658784 bytes` (30M) [`-38168 bytes`, ~ -37KB]
termusic-server: `23586352 bytes` (23M) -> `23586352 bytes` (23M) [-0]

This PR lessens the size of the binaries somewhat

---

lib/src/ueberzug.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/playlist.rs
tui/src/ui/components/podcast.rs
tui/src/ui/components/popups.rs
tui/src/ui/components/tag_editor/te_counter_delete_lyric.rs
tui/src/ui/components/tag_editor/update.rs
tui/src/ui/components/tag_editor/view.rs
tui/src/ui/components/xywh.rs
tui/src/ui/mod.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs
tui/src/ui/model/view.rs
tui/src/ui/model/youtube_options.rs

This PR changes the Error-Popup to accept raw Errors, this way we can fully log the error cause and chain to the log and also to the tui. in some more details:
- move error logging from `mount_error_popup` to `ErrorPopup::new`
- change both function to accept `anyhow::Error` instead of `str`
- add a title to the `ErrorPopup`
some downsides:
the ErrorPopup is [limited to 4 lines of height](https://github.com/tramhao/termusic/blob/e85f574a48befbf4a53560ec8a2200a350c987dd/tui/src/ui/model/view.rs#L436), meaning better printing like the following is not possible until it changes:
```txt
Some Error
Caused by:
0: Some Context
1: Some original Error
```
and instead printed is
```txt
Some Error: Some Context: Some original Error
```
(which in longer chains may get cutoff)

Change tui `mount_error_popup` to accept raw Errors instead of strings

---

CHANGELOG.md

Add it to the changelog, so that it is not forgotten (and for people looking on why we got straight to 0.9.0)

docs(CHANGELOG): add note about 0.8.0

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.md
CHANGELOG.md
server/src/cli.rs
tui/src/cli.rs

This PR does:
- change `log-to-file` to default to `true`
- change `log-to-file` to be set-able (`=false` to disable)
- add issue templates

Log to file by default

---

CHANGELOG.md
server/src/cli.rs
tui/src/cli.rs

This PR basically reverts functional changes from #264 again, because of https://github.com/clap-rs/clap/issues/5421

disable `log-to-file` again for now

---

playback/Cargo.toml
playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpv_backend.rs
playback/src/rusty_backend/mod.rs
server/src/server.rs
tui/src/ui/components/lyric.rs
tui/src/ui/mod.rs

This PR addresses the issues mentioned in #259 regarding the Backend features. Now server can be compiled with less or same features as playback. Some more details:
- Add new `PlayerTrait` function `media_info` to get the current media's title (works on mpv and gst for both radio and normal music, in rusty for now only in radio)
- mark the `Backend` enum as `non_exhaustive`, meaning any case where a `match` against a backend is done, now it needs to be handled if a backend has not been accounted for in the downstream crate
- gst & mpv: clear media_title in-between source changes
- move applying the prefix `Current Playing: ` from backend-specific to TUI where used (fixes mpv not having the prefix)
- tui lyric: avoid some clones / allocations if possible
note the new `playback::MediaInfo` …

Fix server / playback feature Backend problems

---

playback/src/rusty_backend/decoder/mod.rs
playback/src/rusty_backend/mod.rs

This PR refactors some things for the rusty backend to bring it in-line with other backends, in more details:
- deduplicate the decoder loops (to not accidentally forget to change something in the other loop)
- avoid sample buffer allocations if possible
- parse title metadata for non-liveradio media, as the other backends already did it*1
- various small tweaks
*1 the metadata refactor should also make it easier to add new tags to be parsed

Some rusty backend refactors

---

CHANGELOG.md
server/src/cli.rs
tui/src/cli.rs
tui/src/main.rs

This time for real, tested were:
- no argument -> true
- `--log-to-file` -> true
- `--log-to-file=false` -> false
- `--log-to-file=true` -> true
- `--log-to-file=false --log-file /dev/null` -> false
also:
- add `TM_LOGTOFILE` and `TMS_LOGTOFILE` to control `--log-to-file` from a environment variable (cli argument takes precedence)
- dont give the `--log-to-file` argument to the server from the tui (to still have the server log even if the tui does not, use `TMS_LOGTOFILE=false` instead)

feat(cli): enable "log-to-file" by default

---

tui/src/ui/components/podcast.rs
tui/src/ui/components/xywh.rs

This PR refactors some places in the tui where `reqwest::blocking` was used to use the async versions instead.
In addition to that, some slight other changes:
- in `podcast_search_itunes` report the status code on non-OK status
- in `xywh` also check the status code
- in `xywh` send a error if `result.bytes()` fails instead of ignoring
fixes #209

Use more async reqwest instead of blocking

---

tui/src/ui/mod.rs
tui/src/ui/model/update.rs

for example after showing the popup, but then switching to podcast view.
fixes #248

fix(tui): ensure the QuitPopup has the top-most focus

---

tui/src/ui/components/config_editor/mod.rs
tui/src/ui/components/popups/deleteconfirm.rs
tui/src/ui/components/popups/mock_yn_confirm.rs
tui/src/ui/components/popups/mod.rs
tui/src/ui/components/popups/podcast.rs
tui/src/ui/components/popups/quit.rs
tui/src/ui/components/popups/saveplaylist.rs

This PR adds a common No/Yes popup component as `YNConfirm`.
This way we only have one place to change those popups's handling (like adding a key), or finding all the places it is used to change something.

Common confirm popup component

---

playback/src/playlist.rs
tui/src/ui/components/labels.rs
tui/src/ui/components/playlist.rs

This PR does:
- add a comment clarifying which time unit a property is
- refactor `playback::playlist::add_playlist` to accept a array-slice so that extra loops & allocations can be avoided

playlist `add_playlist` accept a slice instead of a specific vec

---

playback/src/gstreamer_backend.rs

This PR adds a HACK to actually set the initial speed in a gst playback.
This needs to be done because gstreamer does not handle seek (speed) events before the pads are activated, which is at some undocumented time (at least from what i have found), so as a workaround it is set in `StreamStart`.
Additionally, because the gstreamer backend does not have any InternalCMD yet (unlike mpv and rusty), it needs to go through the entire server. In extra addition, we dont have a global "re-apply speed property" event, so i had to HACK it with `SpeedUp` & `SpeedDown`, which work, but result in not being able to use the full speed initially (== 30 in gst).
(I also didnt wanna add a event that is only useful to one backend, would like to refactor gst and main events at some point)
PS: in addition, i …

GStreamer fix initial speed not being applied

---

playback/src/rusty_backend/decoder/mod.rs

This PR changes the rusty backend to clear its sample buffer after a seek.
I dont actually hear a audible difference, but i think it is actually more correct to not play the samples from before the seek.
@tramhao what do you think?

fix(playback::rusty): clear already decoded sample buffer after seek

---

playback/src/gstreamer_backend.rs
playback/src/lib.rs
playback/src/mpv_backend.rs
playback/src/rusty_backend/mod.rs
server/src/server.rs

This PR adds a new function for volume & speed prefixed with `add_` to do signed operations, and replaces (and removes) the old `_up` and `_down` functions.
Also the new function(s) provide a default implementation, as it would be the same in all backends.
For now the `PlayerCmd` enum is un-touched, but i plan to also replace the `Up` and `Down` events there with a relative and value.

Refactor `PlayerTrait` to combine `_up` and `_down` function into `add_`

---

.github/workflows/build.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
playback/src/rusty_backend/mod.rs

This PR updates and removes some dependencies, in more details:
- remove unused dependencies
- update some dependencies
- use more specific versions instead of just the major version, see *1 and *2
- Update MSRV thanks to a dependency update
*1 to not accidentally rely on newer features added in newer minor releases
*2 re lib.rs text:
> Cargo does not always pick latest versions of dependencies! Specify the version as clap = "4.5.0". If Cargo.lock ends up having an unexpectedly old version of the dependency, you might get a dependency that lacks features/APIs or important bugfixes that you depend on. This is most likely to happen when using minimal-versions flag, used by users of old Rust versions.

Dependency Updates

---

lib/src/podcast/db.rs

This PR avoids 2 clones when they are actually not necessary thanks to `old_episodes` not being `mut`

refactor(lib::podcast::db::update_episodes): avoid clone if not necessary

---

playback/src/rusty_backend/decoder/mod.rs

This PR does some fixes for the rusty backend's seeking, in more detail:
- seek more accurately by using the provided `required_ts` and skipping packets until at that point (no audible changes for me, but it is technically more correct)
- reset the decoder after a seek when codec is mp3 (https://github.com/pdeljanov/Symphonia/issues/274)

Playback rusty decoder fix some seeking things

---

Cargo.lock
Cargo.toml
lib/Cargo.toml
lib/src/songtag/kugou/mod.rs
lib/src/songtag/kugou/model.rs
lib/src/songtag/migu/mod.rs
lib/src/songtag/migu/model.rs
lib/src/songtag/mod.rs
lib/src/songtag/netease/mod.rs
lib/src/songtag/netease/model.rs
tui/src/ui/components/tag_editor/te_table_lyric_options.rs

This PR refactors some parts in lib::songtag, most notably changing to use async-reqwest instead of blocking, other changes:
- change `Service*::search`'s parameter `types` to be a enum instead of magic numbers
- add some derives to `SongTag` (and dependencies) for logging and comparing
- add tests for the `to_song_info` for each service (except kugou, because of empty response)
- dont serialize and then immediately deserialize the return vectors
- convert `static: &str` to `const: &str`
Now there is only 1 usage of `reqwest::blocking` anymore, that being `lib::podcast` (and a unreferenced module in `playback::rusty::source::http`)

Some lib::songtag Refactors

---

playback/src/lib.rs
playback/src/mpris.rs
server/src/server.rs

This PR refactor the Media-Controls(mpris) to be in a better shape and more responsive, which includes:
- set volume on volume events (instead of on every tick)
- set progress to actual new progress (instead of using the old / stale progress)
- dont start mpris if not wanted (and restart / stop on config change)
- move reloading config logic to a separate function
- general refactors to have some separate functions for mpris things (change volume, handle events, update progress)

Some Media-Controls(mpris) refactors

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This PR removes the feature `blocking` from `reqwest` and updates the CHANGELOG with changes since v0.9.0

Remove feature `blocking` from `reqwest` & update CHANGELOG

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tui/Cargo.toml
tui/src/ui/components/xywh.rs
tui/src/ui/model/mod.rs

This PR updates the TUI's terminal cover printing support by:
- renaming original feature `cover` to `cover-uberzug`
- add possibility to enable viuer's `sixel` feature
- change cover printing to be behind feature flags (to allow completely not having any cover printing compiled-in)
In addition there are some other changes that went alongside this:
- remove commented-out dependencies in `tui`
- remove unused dependencies in `tui`
- remove unnecessary clones
- change error mapping to be contexts instead (to retain the original error's backtrace)
- some slight de-denting of nested match blocks
- in `show_image` consistently pass-on all errors instead of maybe mounting some error (let the calling function handle that)
PS: the default features reflect what the default was before this PR

Update terminal cover printing support

---

lib/src/config/key.rs
lib/src/types.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/playlist.rs
tui/src/ui/components/popups/help.rs
tui/src/ui/model/update.rs

~~Depends on #308 (as otherwise the tests would fail because of clippy)~~
This PR does 2 things:
- rename `Cmus*Queue` things to `AddRandomTracks` and `AddRandomAlbum`
- fix that `AddRandomTracks` made use of `playlist_select_random_album_quantity` instead of `playlist_select_random_track_quantity`

Rename `Cmus*Queue` with more descriptive names

---

README.md

~~Depends on #308 (as otherwise the tests would fail because of clippy)~~
This PR updates the README MSRV mentions to be 1.75 (which is the current actual MSRV)

Fix README MSRV mentions

---

CHANGELOG.md
lib/src/config/theme.rs
lib/src/types.rs
tui/src/ui/components/config_editor/color.rs
tui/src/ui/components/config_editor/general.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/config_editor/mod.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/database.rs
tui/src/ui/components/labels.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/music_library.rs
tui/src/ui/components/playlist.rs
tui/src/ui/components/podcast.rs
tui/src/ui/components/popups/deleteconfirm.rs
tui/src/ui/components/popups/general_search.rs
tui/src/ui/components/popups/help.rs
tui/src/ui/components/popups/podcast.rs
tui/src/ui/components/popups/quit.rs
tui/src/ui/components/popups/saveplaylist.rs
tui/src/ui/components/popups/youtube_search.rs
tui/src/ui/components/progress.rs
tui/src/ui/components/tag_editor/te_counter_delete_lyric.rs
tui/src/ui/components/tag_editor/te_input.rs
tui/src/ui/components/tag_editor/te_select_lyric.rs
tui/src/ui/components/tag_editor/te_table_lyric_options.rs
tui/src/ui/components/tag_editor/te_textarea_lyric.rs
tui/src/ui/components/tag_editor/view.rs
tui/src/ui/model/view.rs

This PR does:
- add color customization `important_popup_*` (like quit, delete, save config, does not include Error)
- add color customization `fallback_*` (instead of relying on `library_*` as fallback, except for tag-editor, database and podcast views)
- refactor `lib::config::theme` to parse colors directly into integers on config / yaml parse, instead of on-demand (and also provides errors)
- change `lib::config::theme::StyleColorSymbol`'s functions (and by extension `ColorTermusic::color`) to not be fallible (thanks to the change above)
re #314 (not fully fixing it as this only concerns important popups and fallbacks, unless considered otherwise)
Note: this PR is basically to make the v2 config transition smoother by not having to change much else in the change to v2

Refactor config theme

---

lib/src/ueberzug.rs

This PR updates how `ueberzug` command error handling works by:
- checking if the `ueberzug` child has exited before trying to write to it
- adding contexts to some errors
- de-duplicate creation of the ueberzug command
re #100

Improve ueberzug command error handling

---

Cargo.lock
Cargo.toml
lib/src/config/mod.rs
lib/src/podcast/mod.rs
lib/src/utils.rs
server/src/cli.rs
server/src/server.rs
tui/src/cli.rs
tui/src/main.rs
tui/src/ui/components/config_editor/general.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/music_library.rs
tui/src/ui/model/mod.rs

This PR refactors the `Settings` and `CLI` fields to use Paths instead of strings where it makes sense, including all other parts that touched that.
In addition to just switching to paths, some functions also now error more correctly on problems instead of being marked "successful" (like import / export)

refactor config & cli to use Path instead of Strings

---

lib/src/config/mod.rs
lib/src/songtag/mod.rs
lib/src/types.rs
tui/src/ui/components/config_editor/color.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/config_editor/mod.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/popups/general_search.rs
tui/src/ui/components/tag_editor/update.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs

This PR derives `Copy´ (among some other derives if missing like `Debug` and `PartialEq` and `Clone`) where it makes sense.
This makes the usage of those types easier and does not require having a reference to 1(to ~3) bytes.

Derive `Copy` (and some other missing derives) where reasonably possible

---

CHANGELOG.md
server/build.rs
tui/build.rs

This PR extends the build.rs scripts to check for specific files to verify that the git repository is actually the termusic repository we expect and not some other like a AUR repository.
Maybe there exists a better way to check if the git repository is correct instead of just checking for specific files in the git toplevel.
i noticed this in https://github.com/tramhao/termusic/issues/320#issuecomment-2132192219

fix(build.rs): check that the git repository is actually termusic

---

CHANGELOG.md
playback/src/discord.rs
playback/src/lib.rs

This PR refactors some things related to the Discord IPC:
- dont start if not necessary (and start after config reload)
- exit discord thread if mpsc is closed
- dont infinitely try to reconnect and block the thread (also to not infinitely stall the commands)
- some slight style changes
- removing the need for `clippy::cast_possible_wrap`

Some discord IPC refactors

---

.github/ISSUE_TEMPLATE/bug.md

because in version 0.9.0 it is not enabled by default and recent issues were opened with `no logs`

chore(issue_template/bug): add some more instructions for enabling logs

---

lib/src/config/v1/key.rs

This PR updates the current config key `BindingForEvent` config layout to be independent of lower library representation.
This was necessary because tuirealm 1.9 upgraded to bits 2.x, which changed its ser/de layout, which would break existing configs for termusic.
re #237
~~Will very likely conflict with #319~~

fix(lib::config::key): change "BindingForEvent" ser/de to be independent of lower lib representation

---

lib/src/playlist/asx.rs
lib/src/playlist/m3u.rs
lib/src/playlist/mod.rs
lib/src/playlist/pls.rs
lib/src/playlist/xspf.rs

This PR updates the playlist parsing (m3u, pls, asx, xspf):
- completely re-implement `pls` parsing
- remove `asx` related code from `xspf`
- update `xspf` to use options over empty strings
- update `asx` to use options over empty strings
- update `asx` to be a little more spec compliant (refuse entries without at least one `title` and `ref href`)
- move the tests to their respective modules
- add more tests to each module
- actually test the detection and redirection of the main playlist decode
- rename all `PlaylistItem` to their respective playlists name
- some slight cleanup (removing unused functions, improving code style, doc-comments / comments)

Refactor playlist parsing

---

.github/workflows/build.yml

This PR tries fixing the recent windows CI builds failing by explicitly installing llvm (using the version that rust also installs).
I do not know enough about the windows build system to know if this is the correct fix or what has changed to lead to the failures.
Currently the Windows CI is failing with:
```txt
error: failed to run custom build command for `soundtouch-ffi v0.2.0`
Caused by:
process didn't exit successfully: `D:\a\termusic\termusic\target\debug\build\soundtouch-ffi-92939d6b2fb188a5\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=TARGET
cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-pc-windows-msvc
cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_msvc
cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
--- stderr …
```

chore(workflows/build): windows: install llvm for clang

---

lib/src/playlist/asx.rs
lib/src/playlist/m3u.rs
lib/src/playlist/mod.rs
lib/src/playlist/pls.rs
lib/src/playlist/xspf.rs
lib/src/sqlite.rs
lib/src/utils.rs

Continuation of #330, changes:
- (unrelated) add some comments to `lib::sqlite`
- replace the manual `Result<_, Box<dyn Error>>` with `anyhow::Result`
- reserve the length of the returned vector in the new vector
- directly parse into `PathBuf` and `Url` instead of using one `String` type
- ^ also be more robust in conversion
- fix to not include the identifier in `xspf` output anymore (why was it there?)

More `lib::playlist` refactoring

---

playback/src/rusty_backend/conversions/sample.rs
playback/src/rusty_backend/stream.rs
tui/src/ui/model/download_tracker.rs

This PR fixes the new warnings that pop-up in rust 1.79 (and error in the CI because of settings)

Fix new Rust 1.79 warnings

---

.github/workflows/build.yml

Because something changed and chocolatey fails if a newer version is already there and does not allow setting version ranges.
excerpt:
```txt
By installing, you accept licenses for the packages.
A newer version of llvm (v18.1.6) is already installed.
Use --allow-downgrade or --force to attempt to install older versions.
Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
- llvm - A newer version of llvm (v18.1.6) is already installed.
Use --allow-downgrade or --force to attempt to install older versions.
```
[full log, likely gone in a few months](https://github.com/tramhao/termusic/actions/runs/9514627773/job/26227184965?pr=336)
PS: i still have no clue why that was a problem in the first place for a week

chore(workflows/build): windows: dont install llvm for clang

---

.github/workflows/build.yml

PR #337 again but with fixed merge conflicts, do we really want to downgrade if it is already available?
Sadly either installing and downgrading or not installing are the only options as chocolatey still does not support installing ranges, only exact versions.

 chore(workflows/build): windows: dont install llvm for clang again

---

lib/src/podcast/mod.rs
lib/src/utils.rs

This PR adds tests and changed to a allocation-less implementation as most places dont actually need a `String` and a `str` is enough

`lib::utils::StringUtils` add tests & avoid allocations

---

CHANGELOG.md
lib/src/config/tui_overlay.rs
lib/src/config/v2/tui/mod.rs
tui/src/main.rs
tui/src/ui/components/xywh.rs

previously it could only be configured via compile options(features) or cli argument.
Known issues:
- changing the hidden status via keybindings does not save the config to disk as the only time the tui config is saves is when using the config editor

feat: allow configuring coverart hidden via config

---

lib/src/config/v1/key.rs
lib/src/config/v2/tui/keys/mod.rs

This PR changes the transition value from `volume_*_1` to `volume_*_2` as the `1` values were broken as those never actually fired in tuirealm (example `SHIFT++` never actually exists and only `NONE+_` is fired).
In addition i reversed the `volume_down` keys in v1 to be consistent with the `volume_up` keys because otherwise it was `SHIFT+_` which is also never fired.
PS: the default value for volume up / volume down (without transition from v1) in v2 is `+` / `-` (no modifiers)

Fix v1 to v2 volume key translation

---

tui/src/ui/components/config_editor/mod.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/footer.rs
tui/src/ui/components/mod.rs
tui/src/ui/components/tag_editor/mod.rs
tui/src/ui/components/tag_editor/te_footer.rs
tui/src/ui/components/tag_editor/view.rs
tui/src/ui/model/view.rs

This PR changes the footer layout to be a consistent `TEXT: <KEY> TEXT: <KEY>` instead of the previous `<KEY> TEXT <KEY> TEXT` in tag-editor and config-editor to be consistent with the main footer layout.
Additionally this also moves all footers to be their own components that were not already.
re https://github.com/tramhao/termusic/discussions/347#discussioncomment-10059747
PS: i have no clue why no tests are running

Change Footer layout to be consistent

---

lib/src/types.rs
tui/src/ui/components/music_library.rs
tui/src/ui/components/popups/help.rs
tui/src/ui/model/update.rs

This PR does a bunch of small changes to the music library widget (or related things), in more details:
- add help entry for `/`(local search) while in podcast view
- rename LIMsg stepin / stepout messages to be consistent
- rename some functions to make more sense
- remove unnecessary convertions and re-allocations where not necessary
- some small changes where less code could be used
- dont repeat handling for "right key" multiple times
- construct search only once, not every loop for `[library_update_search](https://github.com/tramhao/termusic/commit/d8b5be8e7ec8e6e2ca9ebf6762ed3177e6cae2a5)`

Some small Music-Library widget (and related) changes

---

CHANGELOG.md
lib/src/config/v1/mod.rs
lib/src/config/v2/server/mod.rs

fix(lib): change default ip address to "::1" instead of "::"

---

CHANGELOG.md
Cargo.lock
playback/src/lib.rs
server/Cargo.toml
server/src/server.rs

This PR moves the "no backend selected" compile error to the server package instead of the playback package (and does a runtime panic instead).
This is because currently the TUI makes use of the playback package without needing any backends, which makes the release process bad.
re https://github.com/tramhao/termusic/issues/259#issuecomment-2301443314
re https://github.com/tramhao/termusic/issues/358#issuecomment-2301646206
PS: also update the Cargo.lock for the new version as it had not been updated

Move "no backend selected" compile error to sever

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lib/proto/player.proto
lib/src/player.rs
playback/src/lib.rs
server/Cargo.toml
server/src/music_player_service.rs
server/src/server.rs
tui/Cargo.toml
tui/src/ui/mod.rs
tui/src/ui/playback.rs

This PR implements protobuf streaming for server updates to be more immediate instead of a client(tui) always having to poll.
This helps for example when anything changes via mpris controls (like volume or play/pause), instead of there being a delay of ~1-2 seconds, it is (more or less) immediate now ([the delay without streaming is because of client polling being delayed](https://github.com/tramhao/termusic/blob/a0733aba590e76e9f3f3934cdf939ac8bbc6fd77/tui/src/ui/mod.rs#L106-L108)).
Current events implemented for streaming:
- Play State change (Play / Pause)
- Volume change
- Speed change
- Track information changed (This event is not meant for track progress updates, but title changes or track to track changes)
- Missed Events ("Lagged stream")
PS: this also fixes the issue of setting …

Streaming Server Updates

---

Cargo.lock
Cargo.toml
lib/src/config/v1/key.rs
lib/src/config/v2/tui/keys/mod.rs
tui/src/ui/components/config_editor/color.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/database.rs
tui/src/ui/components/labels.rs
tui/src/ui/components/music_library.rs
tui/src/ui/components/playlist.rs
tui/src/ui/components/popups/message.rs
tui/src/ui/components/tag_editor/te_counter_delete_lyric.rs
tui/src/ui/components/tag_editor/te_table_lyric_options.rs
tui/src/ui/components/tag_editor/view.rs
tui/src/ui/mod.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/view.rs
tui/src/ui/utils.rs

This PR updates to tui-realm 2.0 (and related component crates).
tuirealm 1.9 had been known to be laggy (see #237) and we also had config migration trouble, but now we have config translation in-place without being dependent on tuirealm and they have also fixed all the problems that we had encountered:
- Mouse capture enabled by default, but not actual events for it
- no way to disable mouse capture
- events were only polled *once* per event loop, while mouse capture events can generate ~20 events in 50ms

Update to tuirealm 2.0

---

CHANGELOG.md
Cargo.toml
README.md
lib/src/track.rs

This PR fixes a issue where a Track's tag parsing was only looking for the primary tag type lofty sets for that file type, which could lead to errors.
Example: in lofty, `wav` files are set to have `Id3v2` as the primary tags type, but if it only has riff tag type, termusic would not parse anything.
Additionally, this PR enables symphonia's `aiff` support.

Fix Track's tag parsing if there is no primary tag, but a different one & Enable aiff support

---

lib/src/library_db/mod.rs
lib/src/library_db/track_db.rs
lib/src/songtag/mod.rs
lib/src/track.rs
lib/src/utils.rs
playback/src/discord.rs
playback/src/mpris.rs
playback/src/playlist.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/playlist.rs
tui/src/ui/model/update.rs
tui/src/ui/model/view.rs
tui/src/ui/model/youtube_options.rs

This PR mainly refactors `Track` to store less needed / derivable data, in more details:
- refactor Track to not store any initial strings which like `Unsupported` or `Unknown` and have all consuming places decide how to handle `None`
- refactor Track to not store `directory, ext, filename, file` and only store a single `URI|Path` (and derive the other values on-demand
- refactor Track to always require a location, which can either be a `Path` or `Uri`
This PR also does:
- refactor `lib::utils::get_parent_folder` and all functions using it to use `Path`s instead of strings (way less back-and-forth)
- use one single const string for all fallback `Unknown Artist|Title` strings (because of this there is no more `Unsupported?` only `Unknown Artist|Title` or `empty` for Albums)
- change the …

`lib::track::Track` refactor

---

CHANGELOG.md
Cargo.toml

This PR enables rust `lto`, which should not affect the arch lto. I dont fully know why it was disabled, but from my testing it has no problems.
re #372

feat: enable "lto" for "release" profile

---

.github/workflows/build.yml
lib/src/config/v1/theme.rs
lib/src/config/v2/tui/keys/mod.rs
lib/src/track.rs

This PR fixes the recent merge issues:
- the faulty merge of #381 (specifically ccef496a038f92339d04078b166393487e1ed1e0)
- cargo format issues
additionally, this PR also changes to run clippy & fmt in a separate job so that it can fail quicker and be more obvious on a glance what failed. (also all linux & mac didnt actually fail on format issues, only windows)

Fix recent merges & separate lint CI job

---

CHANGELOG.md
lib/src/songtag/lrc.rs
lib/src/track.rs
lib/src/utils.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/tag_editor/view.rs

This PR refactors many parts of the `lib::songtag::lrc` module and touches upon some related lyric things, in more details:
- add tests for LRC parsing and writing
- fix writing milliseconds to LRC format (previously the completely wrong value was used)
- refactor a bunch of stuff to require less heap (string) allocations
- refactor a bunch of stuff to do less (repeated) searching
- general addition of doc-comments
- cleanup unused code / variables / properties

Refactor songtag LRC handling

---

CHANGELOG.md
lib/src/track.rs

This PR changes the track metadata probe to report errors to the log instead of silently ignoring them.
I noticed this while tracking down https://github.com/Serial-ATA/lofty-rs/issues/462, it will make it easier to detect now.
Additionally, return early `for_db`, which was missed with my earlier PR #377.

Report track probe errors

---

tui/src/ui/components/config_editor/update.rs

When using under MacOS, the theme change doesn't work as the string we receive in `ConfigEditorMsg::ThemeSelectLoad` is just the theme name, rather than the full path. This PR tries to fix this by concatenating the full path with the theme name.

Fix unable to change theme

---

CHANGELOG.md
lib/src/playlist/mod.rs
lib/src/utils.rs

This PR fixes a mistake of accidentally inverting `is_absolute`, causing playlist paths to not be absoluteized anymore (and by extension not being able to find the files).
Additionally this PR also renames some variables in `lib::utils::playlist_get_vec` and allocates the vector with the direct capacity.
fixes #387

Fix Playlist not finding paths

---

CHANGELOG.md
lib/src/config/v2/tui/keys/mod.rs
lib/src/config/v2/tui/theme/mod.rs

This PR fixes some config v2 things:
- fix default theme colors (re #401)
- fix themes using `0x` as prefix not being able to load
- fix default keys for `add_random_(songs|album)` being inverted
- add seemingly missing ThemeColor tests
fixes #401

Fix some config v2 things

---

lib/src/config/v2/tui/keys/mod.rs
lib/src/playlist/pls.rs
lib/src/songtag/kugou/model.rs
lib/src/songtag/migu/model.rs
lib/src/songtag/netease_v2/model.rs
playback/src/playlist.rs
playback/src/rusty_backend/decoder/mod.rs
tui/src/main.rs
tui/src/ui/model/youtube_options.rs

This PR fixes some new warnings added with rust  / clippy 1.84.
Also some slight other fixes i noticed while applying the clippy changes:
- rename some variables
- inline some variables

Fix 1.84 clippy warnings

---

CHANGELOG.md
lib/src/config/v1/theme.rs
lib/src/config/v2/tui/theme/mod.rs
lib/src/config/yaml_theme.rs
lib/src/lib.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/model/mod.rs

This PR changes some more theme things:
- relocate the "load and test all themes" test to root and actually try parsing each into `ThemeColors`
- add the default Termusic theme as a preview option
- set a proper theme name for the Default Termusic theme (only on full-on default)
- add `file_name` option to theme config for better pre-select in preview window on first open
- remember index of the selected theme in preview and re-select it on new table
- rename some functions
- dont have `name` and `author` be required in `YAMLThemeColors`
- move preview theme code to own function (instead of being deeply nested in event handling)
~~Draft until #407 is merged and clippy is re-run~~

Refactor some more theme related things

---

lib/src/songtag/mod.rs
lib/src/types.rs
playback/src/playlist.rs
tui/src/ui/components/config_editor/color.rs
tui/src/ui/components/config_editor/general.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/database.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/mod.rs
tui/src/ui/components/music_library.rs
tui/src/ui/components/playlist.rs
tui/src/ui/components/podcast.rs
tui/src/ui/components/popups/deleteconfirm.rs
tui/src/ui/components/popups/general_search.rs
tui/src/ui/components/popups/help.rs
tui/src/ui/components/popups/mock_yn_confirm.rs
tui/src/ui/components/popups/podcast.rs
tui/src/ui/components/popups/saveplaylist.rs
tui/src/ui/components/popups/youtube_search.rs
tui/src/ui/components/progress.rs
tui/src/ui/components/tag_editor/te_input.rs
tui/src/ui/components/tag_editor/te_select_lyric.rs
tui/src/ui/components/tag_editor/te_table_lyric_options.rs
tui/src/ui/components/tag_editor/te_textarea_lyric.rs
tui/src/ui/model/update.rs
tui/src/ui/model/youtube_options.rs

This PR does:
- remove `Msg::None` and replace it with `Option::None` or `Msg::ForceRedraw` where necessary
- decrease amount of string clones in downloads
- move `YoutubeSearch*` variants from `DLMsg` to `YSMsg`
- rename `XYWHMsg::Hide` to `ToggleHidden`
- fix a panic in `playback::playlist::swap_down` when the playlist is empty
~~Draft until https://github.com/tramhao/termusic/pull/407 is merged and clippy is re-run~~
Also related is https://github.com/veeso/tui-realm-stdlib/issues/27

Remove `Msg::None` and remove some clones

---

lib/proto/player.proto
server/src/music_player_service.rs
tui/src/ui/playback.rs

This PR does:
- sort all `rpc` functions into sections
- rename `EmptyReply` to `Empty`
- De-duplicate all empty message types into `Empty`

Cleanup proto definitions

---

tui/src/ui/components/music_library.rs
tui/src/ui/components/popups/deleteconfirm.rs
tui/src/ui/components/popups/mod.rs
tui/src/ui/components/popups/podcast.rs
tui/src/ui/model/update.rs
tui/src/ui/model/view.rs

This PR does:
- change TUI message showing / hiding from a thread to a tokio task
- misc style changes (dedent, doc-comments)
- de-duplicate `Type DELETE to confirm` component handling

Style dedupe

---

.gitignore
CHANGELOG.md
playback/src/lib.rs
playback/src/playlist.rs
playback/src/rusty_backend/sink.rs
tui/src/ui/components/playlist.rs
tui/src/ui/model/mod.rs

This PR refactors & documents playlist-related things, in more details:
- document `tui::components::playlist::playlist_add_*` functions
- document `playback::playlist::Playlist` fields & functions
- fix possible infinite loop in `Playlist::get_random_index`
- report errors in `Playlist::add_track` / `Playlist::add_playlist` instead of silently ignoring them (like "unsupported file type")
- early-return parsing `playlist.log` if file did not exist or is empty
- dont save a empty `0` to `playlist.log` if the playlist is empty, only truncate the file
- some style changes (dedent, simpler calls)
- clear everything in `Playlist::clear` instead of having some residual data
- remove `Playlist::next_track` and only use `Playlist::next_track_index`
- gitignore the `.vscode` directory
Some …

Refactor & document playlist-related things

---

lib/proto/player.proto
lib/src/player.rs
playback/src/lib.rs
server/src/music_player_service.rs
server/src/server.rs
tui/src/ui/mod.rs

This PR improves the Protobuf situation a bit more, details:
- rename some messages to be more generic usable
- change index fields to be `u64` (instead of `u32`)
- change `GeneralPlayer::toggle_gapless` to call through `GeneralPlayer::set_Gapless` (instead of on the backend directly)
- add stream event for "gapless" changes
- document a bunch of things
and finally, and biggest:
Refactor to optionally use callbacks for player events to use instead of static waiting `20ms`. This makes it more reliable by not potentially reading old values and potentially being faster than 20ms.

ProtoBuf renames, type changes & use callbacks instead of static waiting

---

tui/src/ui/components/labels.rs

This PR changes `LabelSpan` to not apply any colors itself and delegates that to the `TextSpan`s inside it.
Without this, the footer may look like the following when using native themes:
re https://github.com/tramhao/termusic/issues/342#issuecomment-2615514711

fix(tui::ui::components::labels::LabelSpan): dont style the "LabelSpan"

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lib/Cargo.toml
lib/src/library_db/mod.rs
tui/Cargo.toml
tui/src/ui/components/music_library.rs

This PR changes the sort for the Music-Library (file explorer) and the Database views (Criteria and Tracks) to be Alphanumerically sorted instead of Lexicographical.
Example current master (lexicographical):
Example with this PR (alphanumeric):
fixes #417
re #138
---
@Sporarum could you test this PR?

Alphanumeric sort for Music-Library & Database

---

lib/src/config/v2/server/mod.rs

This PR fixes a issue with the [nightly clippy runs](https://github.com/tramhao/termusic/actions/runs/13448656742/job/37579070997) that now started complaining about this useless conversion
```txt
error: useless conversion to the same type: `std::path::PathBuf`
--> lib/src/config/v2/server/mod.rs:469:56
|
469 |                 music_dirs: value.music_dir.into_iter().map(Into::into).collect(),
|                                                        ^^^^^^^^^^^^^^^^ help: consider removing
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
= note: `-D clippy::useless-conversion` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::useless_conversion)]`
```

style(lib::config::v2::server::v1_interop): fix nightly clippy complaining about useless conversions

---

CHANGELOG.md
lib/src/config/v2/server/config_extra.rs
lib/src/config/v2/tui/config_extra.rs

This way, the config can be changed if the TUI cant connect.
re https://github.com/tramhao/termusic/issues/402#issuecomment-2691390722

fix(lib::config::v2): save config if the path does not exist

---

Cargo.lock
Cargo.toml
lib/Cargo.toml
lib/src/config/v1/theme.rs
lib/src/config/v2/server/config_extra.rs
lib/src/config/v2/server/mod.rs
lib/src/config/v2/tui/keys/conflict.rs
lib/src/config/v2/tui/keys/mod.rs
lib/src/config/v2/tui/theme/mod.rs
lib/src/songtag/service.rs
playback/src/playlist.rs

This PR switches some of our Error implementations to use `thiserror::Error` to lessen the boilerplate.
Some errors cannot be easily converted 1:1 as `thiserror` either does not support it, or it would be more work than not using `thiserror`, like errors with `Vec`s of Errors or custom `Display` impls.
Additionally, while i was at it i looked at the messages again and tried to improve them a little.

Use `thiserror` when possible

---

lib/src/songtag/kugou/mod.rs
lib/src/songtag/kugou/model.rs
lib/src/songtag/lrc.rs
lib/src/songtag/migu/mod.rs
lib/src/songtag/migu/model.rs
lib/src/songtag/netease_v2/mod.rs
lib/src/songtag/netease_v2/model.rs
lib/src/ueberzug.rs

This PR adds custom errors with `thiserror` for songtag models / parsing.
Note that `anyhow` is still used for all songtag's main error type, to keep some backtrace.
This is a extension on #431

Custom Errors for `songtag` models (parsing)

---

lib/src/config/v1/mod.rs
lib/src/invidious.rs
lib/src/library_db/track_db.rs
lib/src/podcast/db/episode_db.rs
lib/src/podcast/db/file_db.rs
lib/src/podcast/db/migration.rs
lib/src/podcast/db/mod.rs
lib/src/podcast/mod.rs
lib/src/track.rs
lib/src/utils.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/database.rs
tui/src/ui/components/tag_editor/te_counter_delete_lyric.rs
tui/src/ui/model/youtube_options.rs

This PR mainly focuses on doing less broad `allow(unused)`, by moving to more strict `allow(dead_code)` where necessary, or even complete code removal (or moving of code).
Also removes some lints that were not necessary anymore.

Less Clippy broad `allow(unused)` and remove some unused lints

---

Cargo.toml
lib/Cargo.toml
lib/src/lib.rs
playback/Cargo.toml
playback/src/lib.rs
playback/src/mpris.rs
tui/Cargo.toml
tui/src/main.rs

This PR moves most top-level lint settings to be workspace-wide lints.
Also removes the `recursion_limit` setting as it does not seem to be necessary, and the default `128` *should* be enough.

De-duplicate lints into workspace-lints

---

lib/src/config/mod.rs
lib/src/config/server_overlay.rs
lib/src/config/tui_overlay.rs
lib/src/config/v2/mod.rs
lib/src/config/v2/server/config_extra.rs
lib/src/config/v2/server/mod.rs
lib/src/config/v2/tui/config_extra.rs
lib/src/config/v2/tui/keys/mod.rs
lib/src/config/v2/tui/mod.rs
lib/src/config/v2/tui/theme/mod.rs
lib/src/config/v2/tui/theme/styles.rs
lib/src/lib.rs
lib/src/podcast/episode.rs
lib/src/podcast/mod.rs
lib/src/podcast/podcast.rs
lib/src/songtag/lrc.rs
lib/src/songtag/mod.rs
lib/src/taskpool.rs
lib/src/track.rs
lib/src/types.rs
lib/src/utils.rs
lib/src/xywh.rs

This PR un-ignores the `clippy::must_use_candidate` lint and adds it everywhere suggested.
Might conflict with #436

Remove `allow(clippy::must_use_candidate)` from lib

---

CHANGELOG.md
lib/src/ueberzug.rs

Let the `ueberzug` command inherit `stdout`, which is required for outputs like `chafa`.
re #438

fix(lib::ueberzug): let the ueberzug command inherit stdout

---

CHANGELOG.md
lib/src/library_db/mod.rs
lib/src/playlist/mod.rs
lib/src/podcast/mod.rs
lib/src/types.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/lyric.rs
tui/src/ui/components/music_library.rs
tui/src/ui/components/podcast.rs
tui/src/ui/components/popups/message.rs
tui/src/ui/components/popups/podcast.rs
tui/src/ui/model/download_tracker.rs
tui/src/ui/model/update.rs
tui/src/ui/model/youtube_options.rs

This PR mainly focuses on doing less clones, but also does some other slight fixes that would be annoying to put in their separate PRs:
- dont clone where not necessary
- change some functions to not need to clone themself (ie dont take a reference which is always cloned)
- change all search results to start numbering at `1`
- change all search indexes to be usize to prevent early wrapping (rust defaults to `i32` for some reason)
- dont do some things unless in the error case (replace `context` with `with_context`)
- for first db results, dont allocate a full vector, take the first element from the iterator directly
- change `PCMsg::Error` to not have a duplicate `url`(String) as `feed` already contains it

Less clones & consistent search result indexes

---

CHANGELOG.md
lib/src/songtag/mod.rs
tui/src/ui/components/tag_editor/te_counter_delete_lyric.rs
tui/src/ui/components/tag_editor/te_table_lyric_options.rs
tui/src/ui/components/tag_editor/update.rs
tui/src/ui/components/tag_editor/view.rs
tui/src/ui/model/download_tracker.rs

This PR improves the Tag-Editor experience by:
- doing less work (less clones, iterations)
- have the search be non-blocking and have feedback (via download spinner & "Loading.." table text)
- fix possible messed-up display if lyric text was split with `\r\n`
- properly reflect `Delete` Lyric index of the selected index (instead of having based on the length of the array), now it matches the actual behavior of only removing the selected lyric frame (instead of the implied all)
- in Lyric Selection, display the index of the frame (beginning from 1) and if description is empty, fallback to language.
To make the search task non-block, i also changed the `DownloadTracker` to be Send-able across Tasks & Threads.

Tag-Editor improvements

---

Cargo.lock
Cargo.toml

to fix yanked warning for "futures-util@0.3.30":
```txt
warning: package `futures-util v0.3.30` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
re https://github.com/tramhao/termusic/issues/439#issuecomment-2705446723

deps(futures): update to 0.3.31

---

CHANGELOG.md
playback/src/rusty_backend/sink.rs

to match behavior with other backends and to be what would be expected of knowing where in the track we are.
This also fixes #102 to my knowledge, unless i missed something.
This had been messed-up by me in 397a123f30899215813c031a492688e09472d58e.

fix(playback::rusty::sink::append): track time before speed change

---

tui/src/ui/model/youtube_options.rs

This PR removes the seemingly unnecessary sleeps between sending messages `DownloadSuccess` (and `DownloadErr`) and `DownloadComplete`.
fixes #424

fix(tui::ui::model::youtube_options::youtube_dl): remove sleeps between messages

---

lib/src/ueberzug.rs

`ueberzugpp` does not output to stdout, but to stderr from my testing, which is not a problem, but `ueberzugpp-new` currently outputs to stdout instead of stderr, messing-up the display.
This should not be breaking as both projects also output logs to `/tmp/ueberzug-USER.log`.
For context, i opened a issue in the `ueberzugpp-new` repo https://github.com/jstkdng/ueberzugpp-new/issues/5.
re #440

fix(lib::ueberzug): silence stdout output

---

CHANGELOG.md
README.md
lib/src/config/tui_overlay.rs
lib/src/ueberzug.rs
lib/src/xywh.rs
tui/src/cli.rs
tui/src/main.rs
tui/src/ui/components/xywh.rs
tui/src/ui/model/mod.rs

This PR moves existing cli option `--disable-cover` to `--hide-cover` and adds a new `--disable-cover` which will make the TUI behave as if no cover features are compiled-in.
Additionally:
- dont init a ueberzug instance if viuer supports it.
- Log which viuer protocol is used and if ueberzug gets activated.
- random fix when terminal size / height is 0 (instead of a panic)
re #449 and likely #451

Option to disable cover features at runtime

---

CHANGELOG.md
Cargo.lock
tui/Cargo.toml
tui/src/main.rs
tui/src/ui/components/xywh.rs
tui/src/ui/model/mod.rs

This is necessary as viuer will always probe for all enabled protocols on each print until it finds a supported one, but because of likely improper implementation, it could cause a infinite loop of waiting for a response which never comes, freezing the TUI.
re #449
@Porkepix could you test this PR without `--disable-cover` or `--hide-cover` and with features `cover`(all) enabled across multiple TUI starts & tracks?
PS: this PR is marked as DRAFT until confirmed that it fixes the issue.

fix(tui::ui::components::xywh::show_image): force viuer to only use the protocol we probed for

---

Cargo.lock
Cargo.toml
playback/Cargo.toml
playback/src/backends/gstreamer/mod.rs

This PR removes dependency `async_channel` as we already depend on tokio, so we can just use `tokio::sync::mpsc` instead.
Additionally includes some slight formatting changes:
- remove outdated commented-out code
- align variable names with other backends
- convert channel proxy thread to task
- dont have a trait pub that is specific to the backend

playback: remove dependency `async_channel`

---

CHANGELOG.md
lib/proto/player.proto
lib/src/player.rs
playback/src/lib.rs
playback/src/mpris.rs
playback/src/playlist.rs
server/src/music_player_service.rs
server/src/server.rs
tui/src/ui/components/playlist.rs
tui/src/ui/mod.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs
tui/src/ui/music_player_client.rs
tui/src/ui/tui_cmd.rs

This PR refactors the playlist handling to have all playlist state handling completely done server-side, no more `ReloadPlaylist` send from the TUI and no more touching `playlist.log` from the TUI. Some more details:
- doing this required that `Playlist` be shared between `GeneralPlayer`(player thread) and the grpc service, which introduced a lot of `.write()`, `.read()` & `drop(playlist)` noise
- change cryptic function `PlaySelected` to `PlaySpecific` with a index attached, this makes it a lot clearer what this function should do
I know this is quite a big PR but i didnt want to split it into multiple parts as it would otherwise be mixed in terms of calling conventions.
Known Issues:
- events from the TUI are asynchronously handled, as in: the event is send, but the TUI is not blocked …

Playlist completely server side

---

CHANGELOG.md
lib/src/config/v2/tui/theme/mod.rs
lib/src/config/v2/tui/theme/styles.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs

This PR adds a `Native` theme that just passes-through the ASCII Colors instead of setting custom RGB ones.
This allows the usage of the terminal's theme directly, for example useful for `pywal`.
This PR adds a new possible `native` value to `tui.toml` `theme`, which before could only accept hex numbers.
This does NOT allow `native` as a valid value from custom themes(`YAMLTheme`), only for the `tui.toml`.
Due to this being implemented as a normal "Fake" / "No File" Theme, it completely integrates with the selection and preview of themes without having to do much extra.
I think this qualifies as fixes #342.

Add `Native` Theme

---

tui/src/main.rs
tui/src/ui/mod.rs

This solves the issue:
#472 
This will:
1. on quit, probe for `termusic` instances at the same time `termusic` iterates over processes
2. count them if they are not spawned by `termusic` by looking up PID.
3. if there are two or more externally spawned processes, it will skip killing the server.
My code is not very elegant, so I'd like some simple feedback if possible. Thank you!

refuse kill if another instance is running

---

CHANGELOG.md
playback/src/backends/rusty/decoder/mod.rs
playback/src/backends/rusty/sink.rs
playback/src/backends/rusty/source/async_ring/messages.rs
playback/src/backends/rusty/source/async_ring/mod.rs
playback/src/backends/rusty/source/custom_speed.rs
playback/src/backends/rusty/source/mod.rs
playback/src/backends/rusty/source/soundtouch/mod.rs

This PR changes all places we interact with samples to use Sample-Type `f32` instead of the previous `i16`, reasons are (by order):
- in the next version of rodio, Sources will only work on `f32` (https://github.com/RustAudio/rodio/pull/700, possibly rodio `0.21.0`)
- symphonia decodes into `f32` in many formats to my knowledge (but later got converted by us)
- soundtouch already forces use of `f32` samples in the chain, if enabled
- audio systems (like pipewire, pulseaudio) basically also operate on f32 anyway
This means we just have to do less conversions and are better ready for the next rodio version.

feat(playback::rusty): change all sample types from i16 to f32

---

tui/src/ui/model/mod.rs

This fixes a error i didnt check for in #476. This happens because in the TUI Playlist `current_track_index` is `Option` and can only be set if it is within `tracks` bounds, but the current GRPC interface and the server Playlist still have it as non-optional and send `0` even if there are no tracks.

fix(tui::ui::model::load_from_grpc): dont call "set_current_track_index" if there are no tracks

---

CHANGELOG.md
Cargo.lock
lib/src/config/v2/server/mod.rs
lib/src/config/v2/tui/mod.rs
playback/src/backends/rusty/sink.rs
server/Cargo.toml
server/src/server.rs
tui/src/main.rs

This PR mainly adds Unix Domain Socket (or also referred as UDS) support. It is also chosen as the default for `unix` targets. Some notes:
- UDS is currently only available for `unix` targets in tokio & tonic, but windows (since some 10 version) also supports UDS, so it might come to there too
- UDS will be able to be parsed from the config regardless of target
- when migrating from v1 config, `HTTP` is chosen as the default
- if UDS is not available, `HTTP` is chosen as the default
- if UDS is not available, but set in the config, a runtime error will occur
Additionally this PR does, as it somewhat impacted the implementation:
- better gracefully exit instead of calling `::exit(0)` in a `Quit` message (allows tasks to exit gracefully)
- pause & stop the player before exiting. As without …

Add support for Unix Domain Sockets

---

CHANGELOG.md
lib/src/library_db/mod.rs
lib/src/library_db/track_db.rs
lib/src/types.rs
tui/src/ui/components/database.rs
tui/src/ui/components/popups/mock_yn_confirm.rs
tui/src/ui/mod.rs
tui/src/ui/model/update.rs
tui/src/ui/model/view.rs

This PR adds support for the `add single` and `add all` keys to work in the `Result` view / section of the Database layout.
Behavior:
- using `add single`(default `L`) will load that selected thing without question (maybe we should ask for anything other than `Album` or `Artist`?)
- using `add all`(default `shift+L`) will first ask via popup if it is actually wanted, if confirmed, will collect all results and send it to the server, which currently can be massively blocking the TUI as the server is kinda slow resolving the tracks and then responding with done.
fixes #483 
@Sporarum could you review if this is what you wanted?

Allow keys `add single / add all` on Database `Result` view

---

playback/src/playlist.rs

As the server does not make use of `album_photo` at all.
This reduces startup time from 106 seconds to 70 seconds with the test load from #493.
(cold caches; `echo "1" | sudo tee /proc/sys/vm/drop_caches`)
re #493.

perf(playback::playlist): disable "album_photo" path fetching

---

playback/src/playlist.rs
server/src/music_player_service.rs

Once again a new rust version with new pedantic lints has released.
This time though, we will ignore those new lints for now as its either the wanted behavior or not much we can do about it (at least conveniently).

style: fix lints for rust 1.87.0

---

CHANGELOG.md
lib/src/types.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/music_library.rs
tui/src/ui/components/playlist.rs
tui/src/ui/components/tag_editor/update.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs

This PR changes the TUI music library tree loading to be non-blocking and feel responsive by not being locked-up.
Also fixes a bug that the root node is always selected when stepping out of the current directory instead of focusing the stepped-out of node.
Important notes:
- because it is now loading async and the component itself was not touched, means that while something is loading, the user can still navigate and execute things on the tree, like for example starting another load
- the initial `Loading...` text is currently handled via a tree with such a node and a dummy path, but because of this, it can still be navigated. (at least on linux, didnt test this dummy path on windows)
- this pr did not change anything regarding pre-loading a directory, so when encountering a directory …

Change the TUI Music library tree loading to be async

---

CHANGELOG.md
lib/src/track.rs
playback/src/backends/gstreamer/mod.rs
playback/src/backends/mpv/mod.rs
playback/src/playlist.rs

This PR fixes the race condition panic as reported in #506, and also some other things that i encountered while trying to debug this, which includes:
- protect against tracks having empty paths
- the playlist should clamp the `current_track_index` on parse to the actual playlist items
- the playlist should skip empty lines and comment lines on parse
- refactor the mpv time resetting to be consistent on `Event::StartFile`
fixes #506

Fix mpv race condition panic

---

CHANGELOG.md
playback/src/playlist.rs
server/src/server.rs

This PR saves the playlist in intervals of 30 seconds, only if modified. Instead of previously on on exit / quit.
This should prevent losing too much on unexpected circumstances like crash, panic or system lockup.
fixes #513

feat(server): save playlist in intervals

---

CHANGELOG.md
Cargo.lock
Cargo.toml
clippy.toml
lib/Cargo.toml
lib/src/library_db/mod.rs
lib/src/library_db/track_db.rs
lib/src/podcast/db/episode_db.rs
lib/src/podcast/db/file_db.rs
lib/src/podcast/db/migration.rs
lib/src/podcast/db/mod.rs
lib/src/podcast/db/podcast_db.rs
lib/src/songtag/mod.rs
lib/src/track.rs
lib/src/types.rs
lib/src/utils.rs
playback/src/playlist.rs
tui/Cargo.toml
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/components/database.rs
tui/src/ui/components/music_library.rs
tui/src/ui/components/playlist.rs
tui/src/ui/components/popups/general_search.rs
tui/src/ui/components/tag_editor/view.rs
tui/src/ui/model/update.rs
tui/src/ui/model/view.rs
tui/src/ui/utils.rs

This PR moves some things i had done in #511 to a separate PR to include it for the next version and to reduce the review size of #511. In more details what this includes:
- add album artist parsing to the track metadata as a option
- add split album artists and track artists to track metadata as a option
- refactor TUI `database` file to de-duplicate common code paths
- refactor some message types to use better types instead of casting everywhere (`DBMsg::SearchResult`, `PLMsg::Add`)
- refactor some `lib::utils` functions to directly take paths and reduce "if" guards
- make use of `indoc` to have consistent multi-line strings, without having those extra spaces in the compile
- limit vertical size of `DBListCriteria` to the number of table items (now it wont grow beyond that size and …

Deduplicate `database` widget code & some other things from #511

---

CHANGELOG.md
playback/src/backends/gstreamer/mod.rs
playback/src/backends/mpv/mod.rs
playback/src/backends/rusty/mod.rs
playback/src/lib.rs
server/src/server.rs

This PR tries to add a mechanism to track errors in the backend (file not found, unknown codec) and then skips those files.
This works properly on mpv and rusty, but i could not figure out a good way to make it work on gstreamer with enqueuement (currently it only works if it is a error via non-enqueuement), for the reasons why, read the big comment in `gstreamer/mod.rs`.
When a Error event is recieved, the corresponding track will be skipped. If there are 5 continues error-ing tracks, then playback is stopped (similar to as before this PR) to not try infinitely or having to implement a costly "what tracks have already been visited and did the playlist change since?" thingy.
fixes #519
@tramhao Before merging, could you try this and report if you find any errors related to this PR?

Track Backend Errors and skip files

---

CHANGELOG.md
Cargo.lock
Cargo.toml
server/src/logger.rs
tui/src/logger.rs

This PR adds a workaround for the https://github.com/emabee/flexi_logger/issues/194 issue as first noticed in #508.
Also updates `flexi_logger` to the latest version.

Workaround flexi logger file issue

---

playback/src/backends/rusty/mod.rs
server/src/logger.rs
server/src/server.rs

This PR fixes the new clippy warnings added with rust 1.88 now being released.

style: fix clippy 1.88 warnings

---

Cargo.lock
Cargo.toml
README.md
server/src/logger.rs
tui/src/logger.rs

This PR upgrades to `flexi_logger` `0.31.2` and reverts the flexi-logger workaround added in #521 due to flexi_logger handling this case properly now.
This also removes a accidental inclusion of a left-over debug print.
I think after this PR a new version is definitely ready (#517).

Fix accidental inclusion of debug prints & revert flexi_logger workaround

---

CHANGELOG.md
playback/src/lib.rs

Before we only set the volume on volume change and when the config gets re-loaded and souvlaki defaults to `1.0` volume.
fixes #528

fix(playback::mpris): set mpris volume on start

---

CHANGELOG.md
tui/src/main.rs

This changes the connection timeout from 5 seconds to 30 seconds, but print a message on 5 seconds (regardless if connecting is somehow blocking) that it is taking longer than expected.

fix(tui): increase connect timeout and add message

---

tui/src/ui/components/mod.rs
tui/src/ui/components/tag_editor/te_input.rs
tui/src/ui/components/tag_editor/te_select_lyric.rs
tui/src/ui/components/tag_editor/te_table_lyric_options.rs
tui/src/ui/components/tag_editor/te_textarea_lyric.rs

This PR removes some `Copyright (C) 2021 Christian Visintin` where the files / components are not reasonably related to the project the license header mentions. (at least from what i can tell)
related #535

style: remove MIT license headers where not applicable

---

tui/src/ui/components/config_editor/color.rs
tui/src/ui/components/config_editor/general.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/mod.rs
tui/src/ui/components/popups/deleteconfirm.rs
tui/src/ui/components/popups/general_search.rs
tui/src/ui/components/popups/podcast.rs
tui/src/ui/components/popups/saveplaylist.rs
tui/src/ui/components/popups/youtube_search.rs
tui/src/ui/components/tag_editor/te_input.rs
tui/src/ui/components/vendored/README.md
tui/src/ui/components/vendored/mod.rs
tui/src/ui/components/vendored/tui_realm_stdlib_input.rs

This PR vendors file `tui_realm_stdlib/components/input.rs` from https://github.com/veeso/tui-realm-stdlib/pull/37 and applies to throughout where the normal `Input` would otherwise be used.
This is to fix cursor overflow issues and add input scrolling. Key Combo is also updated to include those changes along with fixing some extra problems i noticed while working on it.

Vendor and pre-apply fixes for `tui_realm_stdlib::Input` component

---

Cargo.lock
Cargo.toml
playback/src/backends/rusty/decoder/mod.rs
playback/src/backends/rusty/mod.rs
playback/src/backends/rusty/sink.rs
playback/src/backends/rusty/source/async_ring/messages.rs
playback/src/backends/rusty/source/async_ring/mod.rs
playback/src/backends/rusty/source/cb_done.rs
playback/src/backends/rusty/source/custom_speed.rs
playback/src/backends/rusty/source/mod.rs
playback/src/backends/rusty/source/soundtouch/mod.rs

The long mentioned rodio update is here, the one where `Source` now only accepts `f32` (as mentioned previously in #478).
Aside from the `Source` change to only accept `f32` Samples, the only other noteworthy changes are:
- rename from `current_frame_len` to `current_span_len`
- `OutputStream*` getting a Builder and removing the `*Handle`
- some less important function renames
- cpal `0.16`

deps(rodio): update to 0.21

---

lib/proto/player.proto
lib/src/player.rs
playback/src/lib.rs
playback/src/playlist.rs
server/src/music_player_service.rs
server/src/server.rs
tui/src/ui/components/playlist.rs
tui/src/ui/mod.rs
tui/src/ui/model/mod.rs
tui/src/ui/music_player_client.rs

This PR quite some little things, with the main point being that Progress updates are send as a stream event now (push) instead of fetched from the server (pull).
Additional changes:
- dont run progress & lyric title update functions when not necessary
- properly reflect "Paused" status when the tui is reconnecting to a existing server
- only send `UpdateEvents::PlayStateChanged` events from one single place, otherwise it leads to being forgotten to be send (like previously in `GeneralPlayer::start_play` switching from `Stopped`)
- dont keep "RunningStatus" in `PlayerStats`, instead fetch directly from playlist; avoids de-syncs of those values
- properly initialize `PlayerStats` starting values from config (previously some would only get set on change)
- move "server quit / kill" code to …

Send Progress updates as stream events

---

CHANGELOG.md
lib/src/config/v2/server/backends.rs
playback/src/backends/rusty/mod.rs

Add a new config option under `backends.rusty` to configure the preferred output sample rate.
Now the default output sample rate is set to 48kHz, instead of rodio's previous 44.1kHz.
Note that this is only "preferred" as we will fall-back to other outputs if needed.
Finally, note that there are no limits set for the new config option, but documenting some common sample rates that should be used.

feat(playback::backends::rusty): allow configuring output sample rate

---

CHANGELOG.md
lib/src/config/v2/server/backends.rs
playback/src/backends/mpv/mod.rs

and dont force "ao=pulse" in linux.
This PR is DRAFT until @foxyseta could try it.
re #452

fix(playback::backends::mpv): allow configuring audio-device

---

Cargo.lock
Cargo.toml

This does not improve much, but `parking_lot` *is* known to use less bytes and be slightly faster than std, we also use it directly, so why not enable it for tokio as well?

perf: enable "parking_lot" feature for tokio

---

playback/src/lib.rs

This never worked before, but this was actually only noticeable since 6695ea9c1b879190b810f994c32db770f563711d due to that commint removing the "GetProgress" rpc along with the obsolete "current_track_updated" field.

fix(playback::GeneralPlayer::start_play): also send "TrackChanged" if track is already prefetched(gapless)

---

CHANGELOG.md
tui/src/ui/components/lyric.rs
tui/src/ui/components/progress.rs
tui/src/ui/mod.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs

This PR fixes:
- that switching TO podcast layout did not change the lyric's title (even when going to select a episode)
- that switching TO podcast layout will now always show the selected episode's details (instead of having to first manually select a episode in the list)
- that switching FROM podcast layout to any other to not properly reset lyric contents to their actual non-podcast content
- only run `lyric_update` when actually necessary instead of in every loop
Also add a little more documentation.

Some lyric related changed

---

CHANGELOG.md
tui/src/ui/components/music_library.rs

This PR decreases the time a node takes to open / close in the TUI, this is because `TreeView` component does not report a change on `.perform(TREE_CMD_OPEN|TREE_CMD_CLOSE)`.
Also apply the initial `.perform(TREE_CMD_OPEN)` without requiring a random event first.

Faster TUI MusicLibrary node open/close

---

lib/src/songtag/lrc.rs
lib/src/songtag/mod.rs
tui/src/ui/components/popups/youtube_search.rs
tui/src/ui/components/tag_editor/te_table_lyric_options.rs
tui/src/ui/components/tag_editor/te_track.rs
tui/src/ui/components/tag_editor/update.rs
tui/src/ui/mod.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs
tui/src/ui/model/youtube_options.rs
tui/src/ui/msg.rs

This PR refactors a couple of places to make use of events instead of blocking in-place.
Also removes the spawn_blocking-await in `Model::new` for `YoutubeOptions` as this is no longer required since fffa4e32c694a7b6dc5a5f6b9ff807282e169446.
(This was added in #154 when `YoutubeOptions`/`Invidious` still made use of reqwest-blocking client, which tries to create a runtime within a runtime, which panics in debug mode)

Less `block_in_place` and `block_on`

---

tui/src/ui/components/config_editor/key_combo.rs

This PR mainly refactors the `KeyCombo` draw/view logic to be de-duplicated and use correct styles.
Additionally makes the behavior consistent between Backspace and Delete (previously Delete would also Cancel the open list).
Some notable style changes:
- KeyCombo title is now no longer boder style(default: blue), but Foreground color(default: white)
- KeyCombo open list no longer uses border style (default: blue) for the selected modifer text and input text
- KeyCombo invalid style no longer applies to title, modifier text and modifier list, only border and input text (as the modifiers cannot be invalid currently)

Refactor KeyCombo draw logic

---

CHANGELOG.md
playback/src/playlist.rs
server/src/server.rs

This PR changes the `playback::Playlist::add_tracks` method to collect (and report) errors, but continue adding the remaining tracks.
fixes #565

Continue adding tracks to playlist on error

---

CHANGELOG.md
tui/src/ui/components/progress.rs
tui/src/ui/model/mod.rs
tui/src/ui/model/update.rs

This PR changes the progress component's update to always show the title properly instead of a empty string if there is no current track.
Additionally, always reload data on `GetProgress` response, instead if only the Running status changed (as the running status might not have changed, but volume or progress might have changed when having had missed events).
This is something i noticed while working on #567

fix(tui::ui::components::progress::progress_update_title): always show status

---

README.md

This commit aims for two objectives:
First make it clearer that `make` examples already in the `README` were installing binaries outside of the repo and `target/` directory, in user's home and provide its counterpart to only build and not install them (tell me if that'd be too much, unnecessary and so on).
Secondly, seeing some mentions there, I took the occasion that I currently must work on a mac for $job to try to build `termusic` on it and get rid of some of the uncertainties in `README`, while giving a status on `termusic` on mac.
I could easily verify configuration files location, and then I tried the various build options. I had to tinker and add some dependencies for some of them, using Homebrew.
In the end, I could compile every features providing installation of the required …

chore: README updates about mac and make options

---

CHANGELOG.md
lib/src/config/v2/server/mod.rs
tui/src/ui/components/config_editor/color.rs
tui/src/ui/components/config_editor/general.rs
tui/src/ui/components/config_editor/key_combo.rs
tui/src/ui/components/config_editor/update.rs
tui/src/ui/components/config_editor/view.rs
tui/src/ui/ids.rs
tui/src/ui/msg.rs

This PR changes some things in the config editor:
- split IDs to be better separated
- rework focus handling from `*BlurUp/*BlurDown` messages to simple `Next/Previous` with array (like keys)
- reword some titles to fix typos, better describe what it is about & read more naturally
- add some missing fields (now that it is very easy to actually add fields)
PS: i am considering splitting some of the options to their own tab, or using separators like `<hr>` in HTML (example:)
---
I also am considering adding the backend specific options as their own tab. Or should they rather stay config-file only?
PPS: it would likely be good to refactor the error display to possibly display all lines in the error and not cutting stuff off; also value collection in config editor should likely be looked …

Some polishing for the config editor & add some missing fields
